### PR TITLE
feta: Forward and merge style attributes

### PR DESCRIPTION
**Pull request by StringKe**

### CODE REVIEW

**Comment by mattrothenberg** [comment]
I don't think this API is necessary, as we already expose a className prop.

**Comment by StringKe** [comment]
maybe style will be easier to use than className without creating a css.

for example, I am using chakra ui and I need to modify the style of overflow, and I need to add a css. 

My project does not have any css files.

When using a function like style to create a class package, why don't I pass the style attribute directly?

**Comment by mattrothenberg** [comment]
@StringKe I still don't think you need a `style` prop to achieve this. Here's an example with Chakra UI 👇 

https://codesandbox.io/s/eager-hooks-tml8v?file=/src/App.js

```jsx
return (
    <Box bg="gray.100" p={4} borderBottom="1px">
      <Box
        as={OverflowList}
        border="1px"
        p={3}
        collapseFrom="end"
        minVisibleItems={0}
        items={items}
        itemRenderer={ItemRenderer}
        overflowRenderer={OverflowRenderer}
      />
    </Box>
  );
```

**Comment by StringKe** [comment]
> @StringKe I still don't think you need a `style` prop to achieve this. Here's an example with Chakra UI 👇
> 
> https://codesandbox.io/s/eager-hooks-tml8v?file=/src/App.js
> 
> ```js
> return (
>     <Box bg="gray.100" p={4} borderBottom="1px">
>       <Box
>         as={OverflowList}
>         border="1px"
>         p={3}
>         collapseFrom="end"
>         minVisibleItems={0}
>         items={items}
>         itemRenderer={ItemRenderer}
>         overflowRenderer={OverflowRenderer}
>       />
>     </Box>
>   );
> ```

I know this way of using it, but in Typescript I will encounter a very troublesome type definition error. Do you have a better way to solve it?

image

**Comment by mattrothenberg** [comment]
@StringKe https://codesandbox.io/s/crimson-breeze-u4ew4?file=/src/App.tsx

I will not be providing any more support for this use case.

**Pull request closed without merging**
